### ISSUE TITLE
compose cropping bug

### ISSUE THREAD

**Issue by perronea** [vanandrew/bidssplit#1]
When I try to compose a nifti from 290 sagittal pngs with dimensions (204,292). I want to crop these images so the final dimensions of the nifti are 290x290x203. To do this I am using the command:

./neurosplitter compose /mnt/rose/shared/projects/dHCP_data/train/T2/output/S/ -r S -p 290 203

The output dimensions turn out to be 290x202x203.

This is due to a bug on line 208: 

            data_slice = simple_slice(data_slice, slice(dim1,current_dims[0]-dim2,1), i[0])

should be:

            data_slice = simple_slice(data_slice, slice(dim1,current_dims[i]-dim2,1), i[0])

**Comment by vanandrew** [comment]
Thanks for the heads up. Fixed in 0fc54283259c843532982c9742e50ffccb071b42.

Hopefully that solves the issue, but I'll try a few more test cases before closing the issue.

**Comment by vanandrew** [comment]
Seems to work with all the images I've tested.
